Clients connect to a **Virtual IP**.
create config in /etc/keepalived/keepalived.conf

global_defs {
    script_security
}


vrrp_script chk_postgres {
    script "/etc/keepalived/chk_postgres.sh"
    interval 3
    fall 2
    rise 2
}

vrrp_instance VI_1 {
    state MASTER
    interface br0                  # adjust to your network interface
    virtual_router_id 51
    priority 100                    # higher priority than standby
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        xxx.xxx.xxx.xxx/24 dev eth0  # VIP for client connections
    }
    track_script {
        chk_postgres
    }
    notify "/etc/keepalived/notify.sh"
}
