Create config file:
/etc/postgresql/17/main/repmgr.conf

node_id=1
node_name=DBM01
conninfo='host=DB01 user=repmgr dbname=repmgr connect_timeout=2'
data_directory='/db/data'
log_level=INFO
log_file='/var/log/repmgr/repmgr.log'
log_status_interval=2
pg_bindir='/usr/lib/postgresql/17/bin'
ssh_options='-q -o ConnectTimeout=10'
use_replication_slots=true
connection_check_type='ping'
monitoring_history=true
failover= automatic
promote_command='/usr/bin/repmgr -f /etc/postgresql/17/main/repmgr.conf standby promote --log-to-file'
follow_command='/usr/bin/repmgr -W -f /etc/postgresql/17/main/repmgr.conf standby follow --log-to-file --upstream-node-id=%n'
primary_visibility_consensus=true
repmgrd_service_start_command='sudo /usr/bin/systemctl start repmgrd.service'
repmgrd_service_stop_command='sudo /usr/bin/systemctl stop repmgrd.service'
service_start_command='sudo /usr/bin/systemctl start postgresql@17-main.service'
service_stop_command='sudo /usr/bin/systemctl stop postgresql@17-main.service'
service_restart_command='sudo /usr/bin/systemctl restart postgresql@17-main.service'
service_reload_command='sudo /usr/bin/systemctl reload postgresql@17-main.service'
reconnect_attempts=3
reconnect_interval=3
standby_reconnect_timeout=10
node_rejoin_timeout=10
